// Load env and claim the one server slot before any mutable module initializes.
import './bootstrap.js'

import express from 'express'
import cors from 'cors'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer as createHttpsServer } from 'node:https'
import { createServer as createHttpServer } from 'node:http'
import { readFileSync, existsSync } from 'node:fs'
import { networkInterfaces, homedir } from 'node:os'
import { join } from 'node:path'
import { execSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { healthRouter } from './routes/health.js'
import { diagRouter } from './routes/diag.js'
import { queryRouter } from './routes/query.js'
import { transcribeRouter } from './routes/transcribe.js'
import { displayRouter } from './routes/display.js'
import { transcribeStreamRouter } from './routes/transcribe-stream.js'
import { meetingRouter } from './routes/meeting.js'
import { meetingsRouter } from './routes/meetings.js'
import { openaiCompatRouter } from './routes/openai-compat.js'
import { openaiKeyRouter } from './routes/openai-key.js'
import { messageRefRouter } from './routes/message-ref.js'
import { archiveRouter } from './routes/archive.js'
import { sessionsRouter } from './routes/sessions.js'
import { mediaRouter, mediaBodyParser } from './routes/media.js'
import { promptDraftsRouter } from './routes/prompt-drafts.js'
import { cliDebugRouter } from './routes/cli-debug.js'
import { maintenanceRouter } from './routes/maintenance.js'
import { ttsRouter } from './routes/tts.js'
import { voiceRouter } from './routes/voice.js'
import { glossaryRouter } from './routes/glossary.js'
import { handoffsRouter } from './routes/handoffs.js'
import { recoveryRouter } from './routes/recovery.js'
import { promptEditRouter } from './routes/prompt-edit.js'
import { bookmarksRouter } from './routes/bookmarks.js'
import { prewarmContext } from './lib/context-builder.js'
import { preWarmCLI } from './lib/claude-bridge.js'
import { getCodexRunConfig } from './lib/codex-run-ledger.js'
import {
  startCodexModelCatalogRefresh,
  stopCodexModelCatalogRefresh,
} from './lib/codex-model-catalog.js'
import { startWhisperServer, stopWhisperServer } from './lib/whisper-local.js'
import { initSileroVAD } from './lib/vad-silero.js'
import { initSessionCache } from './lib/session-cache-writer.js'
import { initSpeakerEmbeddings } from './lib/speaker-embeddings.js'
import { logActiveSessionsOnShutdown, startAutoSnapshot } from './lib/conversation.js'
import { getMediaStore } from './lib/media-store.js'
import { listenRequiredServers, type RequiredListener } from './lib/listener-startup.js'
import { serverMetrics } from './lib/server-metrics.js'
import { initializeServerInstanceId } from './lib/server-instance-id.js'
import { appendPrivateEnvBlock, UnsafeUserConfigPathError } from './lib/secure-user-config.js'
import { createQueryJobsRouter } from './routes/query-jobs.js'
import {
  initQueryJobRuntime,
  preparePublicDurableQueryAdmission,
  queryJobCoordinator,
  shutdownQueryJobRuntime,
} from './lib/query-job-runtime.js'
import {
  isAllowedNetworkIp,
  isAllowedNetworkOrigin,
  isTailscaleIpv4,
} from './lib/network-policy.js'
import { timingSafeTokenEqual } from './lib/token-auth.js'
import { isManagedRuntime } from './lib/managed-runtime.js'
import {
  acquireMaintenanceWork,
  MaintenanceLifecycleError,
  maintenanceAdmissionsOpen,
  maintenanceErrorPayload,
} from './lib/maintenance-lifecycle.js'

const app = express()
const PORT = parseInt(process.env.PORT ?? '3141', 10)

// Mode detection — COS mode when a full pipeline directory is configured.
// Standalone (default): glasses + your local Claude Code CLI only.
export const COS_MODE = !!process.env.COS_SCRIPTS_DIR

// Bind host: the glasses' phone app must reach this server over your network or
// mesh (e.g. Tailscale), so the default is 0.0.0.0 (all interfaces). The IP
// allowlist below still blocks untrusted public traffic. Set BIND_HOST=127.0.0.1
// to restrict to localhost only.
const BIND_HOST = process.env.BIND_HOST ?? '0.0.0.0'

// API token — auto-generate if not set so every session is authenticated.
const API_TOKEN_AUTO = !process.env.COS_API_TOKEN
if (isManagedRuntime() && API_TOKEN_AUTO) {
  throw new Error('Managed COS startup requires a pre-provisioned COS_API_TOKEN.')
}
const API_TOKEN = process.env.COS_API_TOKEN ?? `_${randomBytes(32).toString('base64url')}`
process.env.COS_API_TOKEN = API_TOKEN  // make available to routes that check it
// Persist an auto-generated token to ~/.cos-glasses/.env so it SURVIVES restarts.
// Without this, every re-run mints a new token and the app's saved token starts
// returning 401 — the symptom looks like a broken app, not a rotated credential.
let API_TOKEN_PERSISTED = false
if (API_TOKEN_AUTO) {
  try {
    const envDir = join(homedir(), '.cos-glasses')
    appendPrivateEnvBlock(
      join(envDir, '.env'),
      `# auto-generated by the server so the app token survives restarts\nCOS_API_TOKEN=${API_TOKEN}\n`,
    )
    API_TOKEN_PERSISTED = true
  } catch (error) {
    // Read-only homes may continue with a per-session token, but an unsafe
    // symlinked credential path must fail closed instead of being ignored.
    if (error instanceof UnsafeUserConfigPathError) throw error
  }
}

// IP allowlist — only accept connections from localhost, meshnet, and private networks.
// Blocks untrusted public access (coffee-shop WiFi, the open internet) while keeping all
// local + meshnet (Tailscale/CGNAT) + LAN consumers working.
app.use((req, res, next) => {
  const ip = req.ip || req.socket.remoteAddress || ''
  if (!isAllowedNetworkIp(ip)) {
    res.status(403).json({ error: 'forbidden — not on allowed network' })
    return
  }
  next()
})

// Allow localhost + LAN IPs (glasses WebView accesses server over LAN)
app.use(cors({
  origin: (origin, cb) => {
    // Allow requests with no origin (same-origin, curl, SSE) or "null" origin (file:// WebViews like Even Hub)
    if (!origin || origin === 'null') return cb(null, true)
    if (isAllowedNetworkOrigin(origin)) return cb(null, true)
    cb(new Error('CORS blocked'))
  },
}))
// Auth middleware — always active (token is auto-generated if not set)
app.use('/api', (req, res, next) => {
  // Allow health checks, display stream, and client diagnostics without auth.
  // Diagnostics are whitelisted because the client needs to report crashes
  // that may happen before the wizard has supplied an API token, and
  // enforcing auth on a debug telemetry endpoint adds risk during the exact
  // boot window we're trying to observe.
  if (
    req.path === '/health' ||
    req.path === '/display-stream' ||
    req.path === '/diag/client' ||
    req.path === '/diag/health'
  ) return next()
  if (!timingSafeTokenEqual(req.headers['x-cos-token'], API_TOKEN)) {
    return res.status(401).json({ error: 'unauthorized' })
  }
  next()
})

// Fail-closed catch-all for mutation routes that do not own a more specific
// lifecycle lease below. This closes the admission/drain race for secondary
// state-changing APIs (media, sessions, settings, diagnostics) without
// double-owning provider and recording continuations whose routes retain work
// through their true terminal boundary.
app.use('/api', (req, res, next) => {
  if (req.method === 'GET' || req.method === 'HEAD' || req.method === 'OPTIONS') return next()
  const lifecycleOwned = (req.path === '/query-jobs' && req.method === 'POST')
    || req.path === '/query'
    || req.path === '/transcribe'
    || req.path.startsWith('/transcribe-stream')
    || req.path === '/meeting/save'
    || req.path.startsWith('/prompt-drafts')
    || req.path.startsWith('/maintenance/drain')
  if (lifecycleOwned) return next()

  try {
    const lease = acquireMaintenanceWork('api_mutation')
    let released = false
    const release = () => {
      if (released) return
      released = true
      lease.release()
    }
    res.once('finish', release)
    res.once('close', release)
    next()
  } catch (error) {
    if (error instanceof MaintenanceLifecycleError) {
      if (error.retryAfterSeconds != null) res.setHeader('Retry-After', String(error.retryAfterSeconds))
      return res.status(error.status).json(maintenanceErrorPayload(error))
    }
    return res.status(500).json({ error: 'maintenance_internal_error', retryable: false })
  }
})

// Authenticate before parsing large upload bodies. The 16 MB allowance stays
// scoped to /api/media; every other route retains the 10 MB ceiling.
app.use('/api/media', mediaBodyParser)
app.use(express.json({ limit: '10mb' }))

// Request counter — must be before route registrations
app.use((_req, _res, next) => {
  serverMetrics.requestCount++
  next()
})

// API routes
app.use('/api', healthRouter)
app.use('/api', diagRouter)
app.use('/api', createQueryJobsRouter(queryJobCoordinator, {
  prepareAdmission: preparePublicDurableQueryAdmission,
}))
app.use('/api', queryRouter)
app.use('/api', transcribeRouter)
app.use('/api', displayRouter)
app.use('/api', transcribeStreamRouter)
app.use('/api', meetingRouter)
app.use('/api', meetingsRouter)
app.use('/api', openaiKeyRouter)
// v6.3.0 — Message History, cross-day 'reference message N', and history
// recovery for public npx users (previously full-COS-server only).
app.use('/api', messageRefRouter)
app.use('/api', archiveRouter)
app.use('/api', sessionsRouter)
app.use('/api', mediaRouter)
app.use('/api', promptDraftsRouter)
app.use('/api', cliDebugRouter)
app.use('/api', maintenanceRouter)
app.use('/api', ttsRouter)
app.use('/api', voiceRouter)
app.use('/api', glossaryRouter)
app.use('/api', handoffsRouter)
app.use('/api', recoveryRouter)
app.use('/api', promptEditRouter)
app.use('/api', bookmarksRouter)

// OpenAI-compatible endpoint for the G2 Agent (ER "Add Agent")
// Mounted at root — routes are /v1/chat/completions and /v1/models
app.use(openaiCompatRouter)

// Friendly root — this is an API server. The glasses client ships as the Even Hub
// app (the .ehpk), not from here. A browser hitting the host sees a status page.
app.get('/', (_req, res) => {
  res.type('html').send(
    '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>COS Glasses Server</title>' +
    '<body style="font-family:system-ui,sans-serif;max-width:40rem;margin:4rem auto;padding:0 1.25rem;line-height:1.6;color:#111">' +
    '<h1 style="font-size:1.4rem">COS Glasses Server</h1>' +
    '<p>Running. This is the local API for the <strong>COS Glasses</strong> app on Even G2 smart glasses.</p>' +
    '<ul><li>Health: <a href="/api/health">/api/health</a></li>' +
    '<li>Setup guide: <a href="https://www.gotcos.com">gotcos.com</a></li></ul>' +
    '<p style="color:#666;font-size:.9rem">Install the client from the Even Hub, then point it at this server\'s address + token.</p></body>'
  )
})

// Graceful shutdown persists an interrupted terminal before provider abort.
// The bounded force-exit keeps service managers from hanging forever on a
// broken disk while retaining the previous session/catalog/Whisper cleanup.
let gracefulShutdownStarted = false
async function gracefulShutdown(): Promise<void> {
  if (gracefulShutdownStarted) return
  gracefulShutdownStarted = true
  const forceExit = setTimeout(() => process.exit(1), 8_000)
  forceExit.unref?.()
  try {
    await shutdownQueryJobRuntime('server_shutdown')
  } catch (error) {
    console.error('[query-jobs] graceful interruption failed:', error)
  }
  try { logActiveSessionsOnShutdown() } catch { /* best-effort flush */ }
  stopCodexModelCatalogRefresh()
  stopWhisperServer()
  clearTimeout(forceExit)
  process.exit(0)
}
process.on('SIGTERM', () => { void gracefulShutdown() })
process.on('SIGINT', () => { void gracefulShutdown() })

// Crash protection for runtime work. Listener failures are handled separately
// and exit immediately so a supervisor can restart a clean, unified process.
process.on('uncaughtException', (err) => {
  console.error('[CRASH GUARD] Uncaught exception (server stays alive):', err.message)
  console.error(err.stack)
})
process.on('unhandledRejection', (reason: any) => {
  console.error('[CRASH GUARD] Unhandled rejection (server stays alive):', reason?.message ?? reason)
  if (reason?.stack) console.error(reason.stack)
})

// Start HTTPS alongside HTTP — Even Hub WebView prefers HTTPS (iOS ATS).
// Optional: drop cert.pem + key.pem in server/certs/ (e.g. via mkcert) to enable.
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const HTTPS_PORT = parseInt(process.env.HTTPS_PORT ?? '3143', 10)
const certDir = path.join(__dirname, 'certs')
const listeners: RequiredListener[] = []
if (existsSync(path.join(certDir, 'cert.pem'))) {
  const httpsServer = createHttpsServer({
    cert: readFileSync(path.join(certDir, 'cert.pem')),
    key: readFileSync(path.join(certDir, 'key.pem')),
  }, app)
  listeners.push({ server: httpsServer, port: HTTPS_PORT, host: BIND_HOST, label: 'HTTPS' })
} else {
  console.log('[COS API] No certs found — HTTPS disabled (drop cert.pem/key.pem in server/certs to enable)')
}

const httpServer = createHttpServer(app)
listeners.push({ server: httpServer, port: PORT, host: BIND_HOST, label: 'HTTP' })

listenRequiredServers(listeners).then(() => {
  const serverInstanceId = initializeServerInstanceId()
  const startupAdmissionsOpen = maintenanceAdmissionsOpen()
  if (listeners.some(listener => listener.label === 'HTTPS')) {
    console.log(`[COS API] HTTPS server running on https://${BIND_HOST}:${HTTPS_PORT}`)
  }
  console.log(`[COS API] HTTP server running on http://${BIND_HOST}:${PORT}`)
  console.log(`[COS API] Server instance: ${serverInstanceId}`)
  console.log(`[COS API] Mode: ${COS_MODE ? 'COS pipeline' : 'standalone'}`)

  if (startupAdmissionsOpen) {
    void initQueryJobRuntime().then(health => {
      if (process.env.COS_DURABLE_QUERY_JOBS === '1') {
        console.log(`[COS API] Durable query jobs: ${health.store.state} · ${health.store.retainedIdentities} retained`)
      } else {
        console.log('[COS API] Durable query jobs: disabled (set COS_DURABLE_QUERY_JOBS=1 to enable)')
      }
    }).catch(error => {
      // The store remains degraded and rejects admission. Legacy /api/query is
      // still mounted, so disabling the feature flag is an immediate rollback.
      console.error('[COS API] Durable query-job store unavailable:', error)
    })
  } else {
    console.log('[COS API] Startup maintenance gate is closed — durable recovery waits for controller adoption')
  }

  // Print ADDRESSES THE PHONE CAN ACTUALLY REACH. The bind address (0.0.0.0) is
  // not paste-able — enumerate real interfaces and label the Tailscale one.
  try {
    const nets = networkInterfaces()
    const addrs: Array<{ ip: string; label: string }> = []
    for (const [name, infos] of Object.entries(nets)) {
      for (const info of infos ?? []) {
        if (info.family !== 'IPv4' || info.internal) continue
        const isTailscale = isTailscaleIpv4(info.address) || name.startsWith('tailscale')
        addrs.push({ ip: info.address, label: isTailscale ? 'Tailscale — works from anywhere' : `${name} — same Wi-Fi only` })
      }
    }
    if (addrs.length > 0) {
      addrs.sort((a, b) => Number(b.label.startsWith('Tailscale')) - Number(a.label.startsWith('Tailscale')))
      console.log('')
      console.log('[COS API] Server URL for the COS Glasses app:')
      for (const a of addrs) console.log(`[COS API]   http://${a.ip}:${PORT}   (${a.label})`)
    }
  } catch { /* interface enumeration is best-effort */ }

  // Interactive standalone startup may print a newly generated pairing token.
  // Managed startup never generates or logs credentials; COS Control copies the
  // pre-provisioned token through the local pasteboard flow instead.
  if (API_TOKEN_AUTO && !isManagedRuntime()) {
    console.log('')
    console.log(`[COS API] API Token: ${API_TOKEN}`)
    console.log('[COS API]   ^ paste this into the COS Glasses app' + (API_TOKEN_PERSISTED ? ' — saved to ~/.cos-glasses/.env so it stays the same across restarts' : ' (set COS_API_TOKEN in .env for a fixed token)'))
    console.log('')
  }

  // Check Claude CLI availability. Codex-only installs remain fully valid.
  let claudeAvailable = false
  try {
    execSync('claude --version', { timeout: 5000, stdio: 'pipe' })
    claudeAvailable = true
    console.log('[COS API] Claude Code CLI detected')
  } catch {
    console.warn('[COS API] Claude Code CLI not found — install from https://docs.anthropic.com/en/docs/claude-code/getting-started')
    console.warn('[COS API]   Claude models unavailable; Codex models still work when Codex CLI is installed')
  }

  const codexConfig = getCodexRunConfig()
  console.log(`[COS API] Codex mode: ${codexConfig.persistenceEnabled ? 'persistent' : 'ephemeral'} · ${codexConfig.reasoningEffort} · ${codexConfig.trustMode}`)
  console.log(`[COS API] Codex models (${codexConfig.catalogSource}): ${codexConfig.availableModels.map(item => `${item.displayName}=${item.model}`).join(' · ')}`)
  console.log(`[COS API] Codex workdir: ${codexConfig.cwd}`)
  // Refresh immediately and then periodically. The catalog module retains the
  // last-known-good snapshot if Codex is temporarily unavailable.
  if (startupAdmissionsOpen) {
    startCodexModelCatalogRefresh()

    if (COS_MODE) {
      initSessionCache()
      // Pre-warm context cache so first query doesn't wait for the pipeline
      prewarmContext()
    }
    // Start local whisper-server (model stays in RAM for ~50ms transcription)
    startWhisperServer().catch(err => console.error('[startup] Whisper server error:', err))
    // Initialize speaker embeddings (voiceprint-based diarization) — fails soft if model absent
    const embeddingOk = initSpeakerEmbeddings()
    console.log(`[startup] Speaker embeddings: ${embeddingOk ? 'active' : 'disabled (model not found)'}`)
    // Initialize Silero VAD (silence trimming before Whisper) — fails soft if model absent
    const vadOk = initSileroVAD()
    console.log(`[startup] Silero VAD: ${vadOk ? 'active' : 'disabled (model not found)'}`)

    // Pre-warm Claude only when installed so Codex-only startup stays quiet.
    if (claudeAvailable) {
      preWarmCLI().catch(err => console.error('[startup] CLI pre-warm error:', err))
    }

    // Auto-snapshot active sessions every 5 min (survives restarts)
    startAutoSnapshot(5 * 60_000)

    // Durable media GC (staged/reserved expiry + generated-image content TTL).
    getMediaStore().startGC()
  }
}).catch((error: NodeJS.ErrnoException) => {
  console.error(`[COS API] Fatal listener startup: ${error.message}`)
  process.exit(error.code === 'EADDRINUSE' ? 75 : 74)
})
