// The readable meeting, and the two forms of it that leave the machine.
//
// WHAT v1 GOT WRONG, because the shape of the fix follows from it.
//
// v1 floored the attendee block and shipped every other section verbatim. On the
// 2026-08-06 IJO Post-Mortem — where the review asserts exactly ONE voice — all
// 14 unasserted names still reached the clipboard, including one Miles had
// already confirmed was never in the room, as `[Name]:` transcript labels. The
// stated contract, "only asserted voices are named", was false for the largest
// output.
//
// The fix is NOT redaction. Two reasons:
//   1. Transcript labels are EVIDENCE, and they came from the same identifier
//      whose verdict we would be applying — rewriting them is circular and
//      destroys the raw record the reviewer needs to judge for themselves.
//   2. A name in the prose is frequently a person MENTIONED, not one who SPOKE.
//      An action item naming Jessica Thompson does not claim she was in the room.
//      Stripping it would replace one wrong claim with a different one.
//
// So the output carries an ALLOWLIST: who voice matching confirmed, plus a plain
// statement that every other name below is unverified capture output. Honest,
// lossless, and short — a blocklist ran to 14 names on that meeting and 55 on
// another.
//
// v1's second error: it asserted talk shares Control's own panel suppresses. The
// panel hides per-row shares below 60% coverage and says so in orange; the
// clipboard printed "100% of named speech" on a meeting that was 10.5%
// identified, and 49% of real meetings sit under that floor. The artifact that
// LEAVES the machine must be at least as careful as the screen it came from.
//
// Formatting lives here, not in Swift, because Swift has no execution-test
// harness in this project and these strings are the product.

/** One `## Heading` section of a scribe file, in document order. */
export interface ScribeSection {
  heading: string
  /** Body with the heading line removed, scaffolding stripped, edges trimmed. */
  body: string
}

export interface ParsedScribe {
  /** The `# Title` line, or '' when the file has none. */
  title: string
  sections: ScribeSection[]
  summary: string
  topics: string
  decisions: string
  actions: string
  transcript: string
  /**
   * Sections that are none of the above, in document order.
   *
   * v1 discarded these, losing 116,820 characters across the corpus including
   * `Granola Structured Notes (canonical)` — Miles's own write-up — and
   * `Fathom Action Items (with exact timestamps)`. "Copy the meeting" has to
   * copy the meeting.
   */
  extras: ScribeSection[]
}

const HEADING = /^(#{1,6})\s+(.+?)\s*$/
const FENCE = /^\s*(```|~~~)/

/**
 * Strip markdown scaffolding that is structure rather than content.
 *
 * 160 of 227 real scribes wrap the transcript in a `<details>` disclosure and
 * 161 end with a generator stamp. Both land in whatever the final section is, and
 * both are noise in every destination — the stamp especially, because it is
 * generation time and reads like meeting content.
 */
export function cleanBody(body: string): string {
  const kept: string[] = []
  for (const line of body.split('\n')) {
    const t = line.trim()
    if (t === '<details>' || t === '</details>') continue
    if (/^<summary>.*<\/summary>$/i.test(t)) continue
    if (/^\*Generated by .*\*$/i.test(t)) continue
    kept.push(line)
  }
  // Drop trailing rules AND the blank lines between them, left orphaned by the
  // stamp that sat underneath. Popping rules alone stops at the first blank line
  // the stamp left behind, so the rule survived — caught by test, not by reading.
  const trailingNoise = (line: string) =>
    line.trim() === '' || /^\s*(-{3,}|\*{3,}|_{3,})\s*$/.test(line)
  while (kept.length > 0 && trailingNoise(kept[kept.length - 1])) kept.pop()
  return kept.join('\n').trim()
}

/**
 * Split a scribe into its `##` sections.
 *
 * FENCE-AWARE. A `#` inside a fenced code block is code, not a heading. Without
 * this, a fence truncates its section at the first `##` inside it and can lift a
 * shell comment into the meeting title. No real scribe carries a fence today, but
 * the Granola sections are LLM-authored markdown, so one will arrive.
 *
 * `###` subheadings stay INSIDE their parent — Action Items splitting into High
 * Confidence / Needs Review is one section's body, not two sections.
 */
export function parseScribe(markdown: string): ParsedScribe {
  const lines = markdown.replace(/\r\n?/g, '\n').split('\n')
  let title = ''
  const sections: ScribeSection[] = []
  let current: ScribeSection | null = null
  let inFence = false

  for (const line of lines) {
    if (FENCE.test(line)) inFence = !inFence
    if (!inFence) {
      const m = HEADING.exec(line)
      if (m && m[1].length === 1 && !title) { title = m[2].trim(); continue }
      if (m && m[1].length === 2) {
        if (current) sections.push({ ...current, body: cleanBody(current.body) })
        current = { heading: m[2], body: '' }
        continue
      }
    }
    if (current) current.body += line + '\n'
  }
  if (current) sections.push({ ...current, body: cleanBody(current.body) })

  const used = new Set<ScribeSection>()
  /** Exact heading match, first name wins. */
  const exact = (...names: string[]): string => {
    for (const n of names) {
      const s = sections.find(x => x.heading.toLowerCase() === n.toLowerCase() && !used.has(x))
      if (s) { used.add(s); return s.body }
    }
    return ''
  }
  /**
   * CONTAINS match, longest body wins.
   *
   * Prefix matching is the obvious rule and it is WRONG: 113 scribes head the
   * transcript `G2 Speaker-Separated Transcript` — the speaker-attributed one,
   * the most useful thing to hand a model — which does not start with the word.
   * Measured across 1,930 transcript headings, prefix catches 94%, contains 100%.
   * Longest-body separates a real transcript from a short
   * `Transcript Enrichment (from raw recording)` note in the same file.
   */
  const contains = (needle: string): string => {
    const hits = sections
      .filter(x => x.heading.toLowerCase().includes(needle) && !used.has(x))
      .sort((a, b) => b.body.length - a.body.length)
    if (hits.length === 0) return ''
    used.add(hits[0])
    return hits[0].body
  }

  const summary = exact('Summary')
  const topics = exact('Topics Discussed', 'Topics')
  const decisions = exact('Decisions Made', 'Decisions')
  const actions = exact('Action Items', 'Actions')
  const transcript = contains('transcript')
  // Attendees is consumed and DROPPED on purpose: it is the unfloored label list
  // this module exists to replace.
  exact('Attendees')

  return {
    title,
    sections,
    summary: summary || (sections.length === 0 ? cleanBody(markdown) : ''),
    topics,
    decisions,
    actions,
    transcript,
    extras: sections.filter(x => !used.has(x) && x.body.trim().length > 0),
  }
}

/**
 * The meeting's calendar date, as `YYYY-MM-DD`.
 *
 * `startTime` is epoch MILLISECONDS (measured: 1786123940914), not ISO. Slicing
 * the stringified number gave "1786123940" — a plausible-looking date field
 * holding a timestamp. LOCAL date, because the scribe filename uses the local day
 * and a UTC conversion would disagree with the file late in the evening.
 */
export function meetingDate(startTime: unknown): string {
  let ms: number | null = null
  if (typeof startTime === 'number' && Number.isFinite(startTime)) {
    ms = startTime < 1e12 ? startTime * 1000 : startTime
  } else if (typeof startTime === 'string' && startTime.trim()) {
    const numeric = Number(startTime)
    const t = Number.isFinite(numeric)
      ? (numeric < 1e12 ? numeric * 1000 : numeric)
      : Date.parse(startTime)
    if (Number.isFinite(t)) ms = t
  }
  // 0 and negatives are not real capture times; they rendered as "1969-12-31".
  if (ms === null || ms <= 0) return ''
  const d = new Date(ms)
  if (Number.isNaN(d.getTime())) return ''
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

/** A voice as the clipboard should describe it. */
export interface AttendeeLine {
  label: string
  /** False when the review refuses to assert this name. */
  asserted: boolean
  speakingMs: number
  /** Share of identified speech, 0..1, or null when unknown/unnamed. */
  share: number | null
}

/**
 * Coverage below which per-voice shares are NOT reported.
 *
 * Mirrors Control's `speakingCoverage < 0.6` gate exactly, so the clipboard and
 * the panel can never disagree about whether a share is trustworthy. 49% of real
 * meetings sit below it.
 */
export const SHARE_COVERAGE_FLOOR = 0.6

function mmss(ms: number): string {
  const total = Math.max(0, Math.round(ms / 1000))
  const m = Math.floor(total / 60)
  const s = total % 60
  if (m === 0) return `${s}s`
  return s === 0 ? `${m}m` : `${m}m ${s}s`
}

export interface AttendeeRenderOptions {
  /**
   * Identified share of voiced time, 0..1, or null when unknown. Null suppresses
   * shares — failing closed, because unknown coverage cannot justify a
   * precise-looking percentage.
   */
  coverage: number | null
  /**
   * UNION of unattributed speaking time, from the review.
   *
   * Required rather than optional so it cannot be forgotten. Summing per-voice
   * figures double-counts crosstalk: v1 printed "30m 21s across 15 voices" inside
   * a 26-minute meeting while the union on the same review said 22m 17s. The
   * server CHANGELOG states the invariant that sum breaks.
   */
  unattributedMs: number
}

/** The attendee block, floor-applied. */
export function renderAttendees(voices: AttendeeLine[], o: AttendeeRenderOptions): string {
  const named = voices.filter(v => v.asserted).sort((a, b) => b.speakingMs - a.speakingMs)
  const rest = voices.filter(v => !v.asserted)
  const showShares = o.coverage !== null && o.coverage >= SHARE_COVERAGE_FLOOR
  const out: string[] = []
  for (const v of named) {
    const pct = showShares && v.share !== null
      ? ` · ${Math.round(v.share * 100)}% of identified speech`
      : ''
    out.push(`- ${v.label}: ${mmss(v.speakingMs)}${pct}`)
  }
  if (rest.length > 0) {
    out.push(`- Unidentified: ${mmss(o.unattributedMs)} across ${rest.length} ` +
             `voice${rest.length === 1 ? '' : 's'} the review could not name`)
  }
  return out.length > 0 ? out.join('\n') : '- (no voices identified)'
}

/**
 * The provenance block: who was confirmed, and a warning covering everyone else.
 *
 * An ALLOWLIST rather than a blocklist. The prose and transcript below carry raw
 * capture labels, some of which the review rejected, and a reader pasting this
 * into a model has no other way to tell which. Naming the confirmed set is short
 * and complete.
 */
export function renderProvenance(voices: AttendeeLine[], coverage: number | null): string {
  const named = voices.filter(v => v.asserted).map(v => v.label)
  const lines: string[] = [
    named.length > 0
      ? `Voice matching confirmed: ${named.join(', ')}.`
      : 'Voice matching confirmed nobody in this meeting.',
    'Any other name below comes from the raw capture or the write-up and was NOT ' +
    'confirmed. Some may be people mentioned rather than people present.',
  ]
  if (coverage !== null && coverage < SHARE_COVERAGE_FLOOR) {
    lines.push(
      `Only ${Math.round(coverage * 100)}% of the voice in this meeting was ` +
      'identified, so speaking shares are not reported.',
    )
  }
  return lines.join(' ')
}

export interface ClipboardInput {
  title: string
  date: string
  durationMin: number
  attendees: AttendeeLine[]
  scribe: ParsedScribe
  /** Both required, so neither can be omitted. See AttendeeRenderOptions. */
  coverage: number | null
  unattributedMs: number
}

function header(i: ClipboardInput): string[] {
  const when = [i.date, i.durationMin > 0 ? `${i.durationMin} minutes` : '']
    .filter(Boolean).join(' · ')
  const parts = [`# ${i.title || 'Untitled meeting'}`]
  if (when) parts.push(when)
  parts.push(
    '', '## Who spoke',
    renderAttendees(i.attendees, { coverage: i.coverage, unattributedMs: i.unattributedMs }),
    '', renderProvenance(i.attendees, i.coverage),
  )
  for (const [heading, body] of [
    ['Summary', i.scribe.summary],
    ['Topics', i.scribe.topics],
    ['Decisions', i.scribe.decisions],
    ['Action items', i.scribe.actions],
  ] as const) {
    if (body.trim()) parts.push('', `## ${heading}`, body.trim())
  }
  for (const s of i.scribe.extras) parts.push('', `## ${s.heading}`, s.body.trim())
  return parts
}

/** Compact form: for pasting into a message. No transcript. */
export function clipboardSummary(i: ClipboardInput): string {
  const parts = header(i)
  // State that a transcript exists but was omitted. Without this, a reader
  // holding only the summary cannot tell whether one exists at all.
  const tx = i.scribe.transcript.trim()
  if (tx) parts.push('', `_Transcript omitted (${tx.length} characters). Use Copy full for it._`)
  return parts.join('\n') + '\n'
}

/** Full form: everything including the transcript, for pasting into a model. */
export function clipboardFull(i: ClipboardInput): string {
  const parts = header(i)
  const tx = i.scribe.transcript.trim()
  parts.push('', '## Transcript', tx || '(no transcript in this scribe)')
  return parts.join('\n') + '\n'
}
