// What leaves the machine when Miles clicks Copy.
//
// THE FIXTURE IS THE POINT. v1's fixture put the confirmed-absent name ONLY in
// `## Attendees`, so `expect(out).not.toContain('Richard Jenkins')` passed while
// 14 unasserted names shipped in the transcript of every real meeting. Third time
// in one day a green suite hid a defect because the fixture could not reproduce
// production, so this one carries the real shapes: a `[Name]:` transcript label
// for an unasserted voice, that same name in the prose, the `<details>` wrapper
// (160 of 227 real scribes), the generator stamp (161), the
// `G2 Speaker-Separated Transcript` heading (113), and an unrecognised section.

import { describe, expect, it } from 'vitest'
import {
  SHARE_COVERAGE_FLOOR,
  cleanBody,
  clipboardFull,
  clipboardSummary,
  meetingDate,
  parseScribe,
  renderAttendees,
  renderProvenance,
  type AttendeeLine,
} from './meeting-scribe-content.js'

/** Production-shaped: decorated transcript heading, scaffold, stamp, extras. */
const SCRIBE = `# IJO Post-Mortem, Edge Saturation Stalls Deals (G2)

| Duration | 26 minutes |

## Attendees
- Richard Jenkins
- Fourteen others the review never confirmed

## Summary
Reviewed the IJO outcome. Jessica Thompson owns the booth follow-up.

## Topics Discussed
- Edge saturation
- Booth placement

## Decisions Made
- Retract the $199 claim; Tyler could not source the number.

## Action Items

### High Confidence
- [ ] Add a booth-placement requirement (Jessica Thompson)

### Needs Review
- [ ] \`[REVIEW]\` Chase the pricing source

## Granola Structured Notes (canonical)
Miles's own write-up, which v1 threw away.

## G2 Speaker-Separated Transcript
<details>
<summary>Click to expand transcript</summary>

[MU]: So where did IJO land.
[Richard Jenkins]: Edge was everywhere on the floor.

</details>

---

*Generated by Meeting Intelligence System — 2026-08-07 13:01:02*
`

describe('parseScribe', () => {
  it('finds a transcript whose heading does not START with the word', () => {
    // 113 real scribes head it `G2 Speaker-Separated Transcript`. Prefix matching
    // — the obvious rule — misses every one of them.
    const s = parseScribe(SCRIBE)
    expect(s.transcript).toContain('Edge was everywhere on the floor')
  })

  it('strips the details wrapper and the generator stamp', () => {
    const s = parseScribe(SCRIBE)
    expect(s.transcript).not.toContain('<details>')
    expect(s.transcript).not.toContain('<summary>')
    expect(s.transcript).not.toContain('Generated by Meeting Intelligence')
    expect(s.transcript.trimEnd().endsWith('Edge was everywhere on the floor.')).toBe(true)
  })

  it('keeps sections it does not recognise instead of dropping them', () => {
    // v1 discarded 116,820 chars corpus-wide, including this one.
    const s = parseScribe(SCRIBE)
    expect(s.extras.map(x => x.heading)).toContain('Granola Structured Notes (canonical)')
    expect(s.extras.find(x => x.heading.startsWith('Granola'))!.body).toContain('threw away')
  })

  it('drops the unfloored Attendees list entirely', () => {
    const s = parseScribe(SCRIBE)
    expect(s.extras.map(x => x.heading)).not.toContain('Attendees')
  })

  it('keeps ### subheadings inside their parent section', () => {
    const s = parseScribe(SCRIBE)
    expect(s.actions).toContain('High Confidence')
    expect(s.actions).toContain('Needs Review')
    expect(s.sections.map(x => x.heading)).not.toContain('High Confidence')
  })

  it('does not treat a # inside a fenced code block as a heading', () => {
    const fenced = '# Real Title\n\n## Transcript\n[MU]: run this\n\n```sh\n# deploy.sh --force\n## not a heading\n```\n\n[MU]: done.\n'
    const s = parseScribe(fenced)
    expect(s.title).toBe('Real Title')
    expect(s.sections.map(x => x.heading)).toEqual(['Transcript'])
    expect(s.transcript).toContain('done.')
  })

  it('prefers the longest transcript when a file has two candidates', () => {
    const two = '# T\n\n## Transcript Enrichment (from raw recording)\nshort note.\n\n## G2 Speaker-Separated Transcript\n' + 'x'.repeat(400) + '\n'
    expect(parseScribe(two).transcript.length).toBeGreaterThan(300)
  })

  it('normalises CRLF', () => {
    const s = parseScribe('# T\r\n\r\n## Summary\r\nline one.\r\n')
    expect(s.summary).toBe('line one.')
  })

  it('treats a heading-less file as the summary', () => {
    const s = parseScribe('loose notes, no headings')
    expect(s.summary).toBe('loose notes, no headings')
  })

  it('survives an empty file', () => {
    const s = parseScribe('')
    expect(s.title).toBe('')
    expect(s.transcript).toBe('')
    expect(s.extras).toEqual([])
  })
})

describe('cleanBody', () => {
  it('drops a trailing rule orphaned by the stamp above it', () => {
    expect(cleanBody('text\n\n---\n\n*Generated by X — now*\n')).toBe('text')
  })
  it('leaves a rule that is real content alone', () => {
    expect(cleanBody('before\n\n---\n\nafter')).toBe('before\n\n---\n\nafter')
  })
})

const VOICES: AttendeeLine[] = [
  { label: 'MU', asserted: true, speakingMs: 600_000, share: 0.6, isOwner: false, confirmedByHuman: false },
  { label: 'Gina Obert', asserted: true, speakingMs: 400_000, share: 0.4, isOwner: false, confirmedByHuman: false },
  { label: 'Richard Jenkins', asserted: false, speakingMs: 30_000, share: null, isOwner: false, confirmedByHuman: false },
  { label: 'Ext', asserted: false, speakingMs: 120_000, share: null, isOwner: false, confirmedByHuman: false },
]
/** The review's UNION for the unnamed voices — deliberately LESS than 30+120. */
const UNION_MS = 100_000
const HIGH = { coverage: 0.9, unattributedMs: UNION_MS, voicedMs: 0, durationMs: 0 }
const LOW = { coverage: 0.105, unattributedMs: UNION_MS, voicedMs: 0, durationMs: 0 }

describe('renderAttendees', () => {
  it('names only asserted voices, with time and share', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).toContain('- MU: 10m · 60% of identified speech')
    expect(out).toContain('- Gina Obert: 6m 40s · 40% of identified speech')
  })

  it('NEVER names an unasserted voice in the attendee block', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).not.toContain('Richard Jenkins')
    expect(out).not.toContain('Ext')
  })

  // v1 summed per-voice figures and printed 30m 21s inside a 26-minute meeting.
  it('uses the review UNION, not the sum of per-voice times', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).toContain('- Unidentified: 1m 40s across 2 voices the review could not name')
    expect(out).not.toContain('2m 30s')
  })

  // The panel suppresses shares below this; the clipboard must too.
  it('SUPPRESSES shares below the coverage floor', () => {
    const out = renderAttendees(VOICES, LOW)
    expect(out).toContain('- MU: 10m')
    expect(out).not.toContain('%')
  })

  it('suppresses shares when coverage is unknown, failing closed', () => {
    expect(renderAttendees(VOICES, { coverage: null, unattributedMs: UNION_MS, voicedMs: 0, durationMs: 0 })).not.toContain('%')
  })

  it('emits no em dash or arrow, per the standing rule for generated copy', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).not.toContain('—')
    expect(out).not.toContain('→')
  })

  it('says so when nothing was identified', () => {
    expect(renderAttendees([], HIGH)).toBe('- (no voices identified)')
  })

  it('formats a whole minute without a bare 0s', () => {
    const one: AttendeeLine[] = [{ label: 'A', asserted: true, speakingMs: 60_000, share: 1, isOwner: false, confirmedByHuman: false }]
    const out = renderAttendees(one, HIGH)
    expect(out).toContain('- A: 1m')
    expect(out.includes('1m 0s'), 'bare 0s seconds').toBe(false)
    // And a lone named voice gets no share: "100% of identified speech" is
    // always true and reads as "he did all the talking".
    expect(out.includes('%'), 'share printed for a single named voice').toBe(false)
  })
})

describe('renderProvenance', () => {
  it('names the confirmed set as an allowlist', () => {
    const out = renderProvenance(VOICES, 0.9)
    expect(out).toContain('Names established here:')
    expect(out).toMatch(/"MU"/)
    expect(out).toMatch(/"Gina Obert"/)
  })

  it('warns that any other name is unconfirmed, and may be merely mentioned', () => {
    const out = renderProvenance(VOICES, 0.9)
    expect(out).toContain('was NOT')
    expect(out).toContain('mentioned rather than people present')
  })

  it('states the coverage figure when it is below the floor', () => {
    expect(renderProvenance(VOICES, 0.105)).toContain('Only 11% of the voice')
  })

  it('is explicit when nobody was confirmed', () => {
    const none = VOICES.filter(v => !v.asserted)
    expect(renderProvenance(none, 0.05)).toContain('No name in this meeting was established')
  })
})

const INPUT = {
  title: 'IJO Post-Mortem',
  date: '2026-08-06',
  durationMin: 26,
  attendees: VOICES,
  scribe: parseScribe(SCRIBE),
  coverage: 0.105,
  unattributedMs: UNION_MS,
  voicedMs: 0, durationMs: 0,
  domain: 'quilt',
  capturedChars: 0,
  removed: [],
}

describe('clipboard forms', () => {
  it('summary omits the transcript but says that it did', () => {
    const out = clipboardSummary(INPUT)
    expect(out).toContain('## Who spoke')
    expect(out).not.toContain('Edge was everywhere on the floor')
    expect(out).toContain('Transcript omitted')
  })

  // THE BLOCKER. An unasserted name reaches the body legitimately (transcript
  // label, prose mention) — so the output MUST carry the correction with it.
  it('carries the provenance warning wherever an unasserted name can appear', () => {
    for (const out of [clipboardSummary(INPUT), clipboardFull(INPUT)]) {
      expect(out).toContain('Names established here:')
      expect(out).toContain('was NOT confirmed')
    }
  })

  it('never lets the unfloored Attendees list through', () => {
    const out = clipboardFull(INPUT)
    expect(out).not.toContain('Fourteen others the review never confirmed')
  })

  it('full carries the transcript, scaffolding already stripped', () => {
    const out = clipboardFull(INPUT)
    expect(out).toContain('Edge was everywhere on the floor')
    expect(out).not.toContain('<details>')
    expect(out).not.toContain('Generated by Meeting Intelligence')
    expect(out.length).toBeGreaterThan(clipboardSummary(INPUT).length)
  })

  it('carries unrecognised sections into both forms', () => {
    for (const out of [clipboardSummary(INPUT), clipboardFull(INPUT)]) {
      expect(out).toContain('## Granola Structured Notes (canonical)')
      expect(out).toContain('threw away')
    }
  })

  it('reports no share anywhere when coverage is below the floor', () => {
    // 26-minute meeting at 10.5% coverage: v1 printed "100% of named speech".
    expect(clipboardFull(INPUT)).not.toContain('of identified speech')
  })

  it('reports shares when coverage clears the floor', () => {
    const out = clipboardFull({ ...INPUT, coverage: 0.9 })
    expect(out).toContain('% of identified speech')
  })

  it('says when a transcript genuinely does not exist', () => {
    const noTx = { ...INPUT, scribe: parseScribe('# T\n\n## Summary\nshort.') }
    expect(clipboardFull(noTx)).toContain('(no transcript in this scribe)')
    expect(clipboardSummary(noTx)).not.toContain('Transcript omitted')
  })

  it('omits an empty date or duration rather than printing a bare separator', () => {
    const bare = clipboardSummary({ ...INPUT, date: '', durationMin: 0 })
    expect(bare.split('\n')[1]).not.toMatch(/^\s*·/)
    expect(bare).not.toContain('0 minutes')
  })

  it('the floor is the same constant the panel uses', () => {
    expect(SHARE_COVERAGE_FLOOR).toBe(0.6)
  })
})

describe('meetingDate', () => {
  it('converts epoch milliseconds to a calendar date', () => {
    expect(meetingDate(1786123940914)).toMatch(/^\d{4}-\d{2}-\d{2}$/)
    expect(meetingDate(1786123940914)).not.toContain('1786')
  })
  it('tolerates epoch seconds and numeric strings', () => {
    expect(meetingDate(1786123940)).toBe(meetingDate(1786123940914))
    expect(meetingDate('1786123940914')).toBe(meetingDate(1786123940914))
  })
  it('accepts an ISO string', () => {
    expect(meetingDate('2026-08-07T12:00:00.000Z')).toMatch(/^2026-08-0[678]$/)
  })
  it('returns empty for junk, and for 0 or negative rather than 1969', () => {
    for (const x of [undefined, null, '', 'not a date', {}, NaN, 0, -1]) {
      expect(meetingDate(x)).toBe('')
    }
  })
})

// ---------------------------------------------------------------------------
// Second /qa round. Each of these fails if its guard is removed — verified by
// mutation, not by the suite going green.
// ---------------------------------------------------------------------------

const BASE = {
  title: 'T', date: '2026-08-07', durationMin: 30,
  attendees: [] as AttendeeLine[], scribe: parseScribe('# T'),
  coverage: 0.9, unattributedMs: 0, voicedMs: 0, durationMs: 0, domain: '', capturedChars: 0, removed: [],
}

const A = (label: string, o: Partial<AttendeeLine> = {}): AttendeeLine => ({
  label, asserted: true, speakingMs: 60_000, share: 0.5,
  isOwner: false, confirmedByHuman: false, ...o,
})

describe('provenance names the WARRANT, not "voice matching" for all three', () => {
  it('credits the wearer exemption as wearing the device', () => {
    const out = renderProvenance([A('MU', { isOwner: true })], 0.9)
    expect(out).toMatch(/"MU" by wearing the device/)
    expect(out).not.toMatch(/"MU" by voice match/)
  })

  it('credits a human-typed name to the human', () => {
    const out = renderProvenance([A('Luke Henry', { confirmedByHuman: true })], 0.9)
    expect(out).toMatch(/"Luke Henry" because a human named that voice/)
    expect(out).not.toMatch(/"Luke Henry" by voice match/)
  })

  it('credits only a real cosine match to voice matching', () => {
    const out = renderProvenance([A('Niala Samnarine')], 0.9)
    expect(out).toMatch(/"Niala Samnarine" by voice match/)
  })

  it('separates all three warrants in one meeting', () => {
    const out = renderProvenance([
      A('MU', { isOwner: true }),
      A('Niala Samnarine'),
      A('Luke Henry', { confirmedByHuman: true }),
    ], 0.9)
    expect(out).toMatch(/"MU" by wearing the device; "Niala Samnarine" by voice match; "Luke Henry" because a human named that voice/)
  })

  it('quotes labels so a comma inside one cannot read as two people', () => {
    expect(renderProvenance([A('Smith, John')], 0.9)).toMatch(/"Smith, John"/)
  })

  it('warns that a different SPELLING of a confirmed name is still unconfirmed', () => {
    // Labels are `MU` while the prose says "Miles"; the correction chain is
    // documented as Ext -> Luke H -> Luke Henry. A reader applying a
    // names-only rule literally would mis-read both.
    expect(renderProvenance([A('MU', { isOwner: true })], 0.9))
      .toMatch(/any different spelling of the ones just listed/)
  })
})

describe('the compact form stays compact', () => {
  const twoTranscripts = [
    '# Two Transcripts',
    '## Summary', 'short summary',
    '## Transcript', 'A'.repeat(4000),
    '## G2 Speaker-Separated Transcript', 'B'.repeat(3000),
  ].join('\n')

  it('never ships a transcript in clipboardSummary when a scribe has two', () => {
    const scribe = parseScribe(twoTranscripts)
    const sum = clipboardSummary({ ...BASE, scribe })
    expect(sum.includes('A'.repeat(200)), 'winning transcript leaked into the summary').toBe(false)
    expect(sum.includes('B'.repeat(200)), 'losing transcript leaked into the summary').toBe(false)
  })

  // The two-transcript test above passes even with the consume-all guard
  // REVERTED, because both fixtures also exceed the size gate — two guards
  // overlapping, so neither is isolated. A SMALL second transcript separates
  // them: it slips under the size gate and only the consume-all guard stops it.
  it('omits a SMALL second transcript from the summary (isolates consume-all)', () => {
    const scribe = parseScribe([
      '# Small Loser', '## Summary', 'short',
      '## Transcript', 'A'.repeat(4000),
      '## G2 Speaker-Separated Transcript', '[MU]: a short but real transcript turn',
    ].join('\n'))
    expect(scribe.otherTranscripts.length).toBe(1)
    const sum = clipboardSummary({ ...BASE, scribe })
    expect(sum.includes('a short but real transcript turn'),
      'a small second transcript reached the no-transcript form').toBe(false)
    expect(clipboardFull({ ...BASE, scribe }).includes('a short but real transcript turn')).toBe(true)
  })

  it('keeps the loser in the FULL form so nothing is lost', () => {
    const scribe = parseScribe(twoTranscripts)
    const full = clipboardFull({ ...BASE, scribe })
    expect(full.includes('A'.repeat(200))).toBe(true)
    expect(full.includes('B'.repeat(200)), 'second transcript was dropped').toBe(true)
  })

  it('size-gates a large extra even under an innocent heading', () => {
    // One real scribe hides a full transcript under `G2 Glasses Enrichment`.
    // A keyword list cannot catch that; a size ceiling can.
    const scribe = parseScribe([
      '# Innocent', '## Summary', 'brief',
      '## G2 Glasses Enrichment (Combined)', 'C'.repeat(9000),
    ].join('\n'))
    const sum = clipboardSummary({ ...BASE, scribe })
    expect(sum.includes('C'.repeat(200))).toBe(false)
    expect(sum).toMatch(/Omitted from the summary \(9000 characters\)/)
    expect(clipboardFull({ ...BASE, scribe }).includes('C'.repeat(200))).toBe(true)
  })

  it('keeps a small extra in BOTH forms', () => {
    const scribe = parseScribe(['# S', '## Summary', 'brief', '## Granola Notes', 'a real note'].join('\n'))
    expect(clipboardSummary({ ...BASE, scribe })).toMatch(/a real note/)
  })
})

describe('a derived note is never relabelled as the transcript', () => {
  it('prints the section\'s own heading', () => {
    const scribe = parseScribe([
      '# Pete Silas 1-1', '## Summary', 's',
      '## Transcript Enrichment (from raw recording)', 'derived analysis, not speech',
    ].join('\n'))
    const full = clipboardFull({ ...BASE, scribe })
    expect(full).toMatch(/## Transcript Enrichment \(from raw recording\)/)
    expect(/\n## Transcript\n/.test(full), 'derived analysis was presented as the transcript').toBe(false)
  })

  it('never lets an attendee heading become the transcript', () => {
    const scribe = parseScribe(['# A', '## Attendees (from transcript)', '- Someone Unverified'].join('\n'))
    expect(scribe.transcript).toBe('')
    expect(clipboardFull({ ...BASE, scribe }).includes('Someone Unverified')).toBe(false)
  })
})

describe('cleanBody strips scaffolding without eating content', () => {
  it('removes internal pipeline markers', () => {
    expect(cleanBody('real content\n<!-- g2-needs-domain-review -->')).toBe('real content')
  })
  it('removes <details> with attributes', () => {
    expect(cleanBody('<details open>\nbody\n</details>')).toBe('body')
  })
  it('keeps a mid-body italic line that merely starts like our stamp', () => {
    // The old unanchored filter deleted this wherever it appeared. Position is
    // the real invariant: a footer is trailing, a sentence is not.
    const out = cleanBody('*Generated by the design team*\nand then real content')
    expect(out).toMatch(/design team/)
    expect(out).toMatch(/real content/)
  })
  it('still removes our own stamp', () => {
    expect(cleanBody('body\n*Generated by COS Meeting Intelligence System*')).toBe('body')
  })
})

describe('time and date edges', () => {
  it('renders a non-finite duration as 0s rather than NaN', () => {
    expect(renderAttendees([A('X', { speakingMs: NaN })], { coverage: 0.9, unattributedMs: 0, voicedMs: 0, durationMs: 0 })).toMatch(/X: 0s/)
  })
  it('rejects an implausibly small epoch instead of printing 1969', () => {
    expect(meetingDate(1)).toBe('')
  })
  it('reads a date-only string as that local date', () => {
    expect(meetingDate('2026-08-06')).toBe('2026-08-06')
  })
})

describe('a name the human explicitly removed', () => {
  // 2026-08-07: Miles removed "Clem Ukaoma" from a call that was only him and
  // Queen. All 8 label sites were rewritten; the summary still opened
  // "Miles, Queen, and Clem talk through..." and the payload said nothing.
  const scribe = parseScribe([
    '# Generational Trauma And Parenting Fears (G2)',
    '## Summary', 'Miles, Queen, and Clem talk through the fallout.',
    '## Transcript', '[Unidentified 1]: reclose that is how you close it',
  ].join('\n'))
  const removed = [{ label: 'Clem Ukaoma', proseStale: true }]

  it('states the removal, in both forms', () => {
    for (const out of [
      clipboardSummary({ ...BASE, scribe, removed }),
      clipboardFull({ ...BASE, scribe, removed }),
    ]) {
      expect(out).toMatch(/You removed "Clem Ukaoma" from this meeting/)
      expect(out).toMatch(/treat every mention of it as a capture error/)
    }
  })

  it('does NOT rewrite the prose', () => {
    // Substituting into a written sentence mangles grammar and can hit the wrong
    // person. The record stays; the correction travels beside it.
    expect(clipboardSummary({ ...BASE, scribe, removed })).toMatch(/Miles, Queen, and Clem talk through/)
  })

  it('is quieter when the prose does not carry the name', () => {
    const out = clipboardSummary({
      ...BASE, scribe, removed: [{ label: 'Clem Ukaoma', proseStale: false }],
    })
    expect(out).toMatch(/You also removed "Clem Ukaoma"/)
    expect(out).not.toMatch(/still uses the name/)
  })

  it('says nothing at all when nobody was removed', () => {
    expect(clipboardSummary({ ...BASE, scribe })).not.toMatch(/You removed/)
  })
})

describe('the overlap note is gated on meeting LENGTH, not voiced time', () => {
  const two = (a: number, b: number): AttendeeLine[] => [
    { label: 'MU', asserted: true, speakingMs: a, share: 0.6, isOwner: true, confirmedByHuman: false },
    { label: 'Queen Ukaoma', asserted: true, speakingMs: b, share: 0.4, isOwner: false, confirmedByHuman: false },
  ]

  it('stays QUIET on ordinary overlap inside the meeting length', () => {
    // 21m + 10m of speech in a 55-minute meeting: they overlap (the voiced union
    // is smaller than the sum) but the rows do not exceed the meeting, so there
    // is nothing confusing to explain. Gating on voicedMs fired here, on 16 of
    // 23 real meetings — boilerplate, not signal.
    const out = renderAttendees(two(21 * 60_000, 10 * 60_000), {
      coverage: 0.9, unattributedMs: 0, voicedMs: 28 * 60_000, durationMs: 55 * 60_000,
    })
    expect(out.includes('these overlap'), 'fired inside the meeting length').toBe(false)
  })

  it('SPEAKS when the rows add past the meeting length', () => {
    // The real 66-minute meeting whose displayed rows totalled 71m9s:
    // 23m29 + 18m6 + 15m29 + 5m2 named = 62m6, plus 9m3 unidentified.
    const real: AttendeeLine[] = [
      ['Jeremy Sokolic', 23 * 60_000 + 29_000], ['Graham Hoffman', 18 * 60_000 + 6_000],
      ['MU', 15 * 60_000 + 29_000], ['Silas Larson', 5 * 60_000 + 2_000],
    ].map(([label, ms]) => ({
      label: label as string, asserted: true, speakingMs: ms as number,
      share: 0.25, isOwner: label === 'MU', confirmedByHuman: false,
    }))
    real.push({ label: 'Unidentified 1', asserted: false, speakingMs: 0, share: null,
                isOwner: false, confirmedByHuman: false })
    const out = renderAttendees(real, {
      coverage: 0.9, unattributedMs: 9 * 60_000 + 3_000,
      voicedMs: 40 * 60_000, durationMs: 66 * 60_000,
    })
    expect(out).toMatch(/these overlap/)
    expect(out).toMatch(/more than the 66m the meeting ran/)
  })

  it('stays quiet when the duration is unknown rather than guessing', () => {
    const out = renderAttendees(two(99 * 60_000, 99 * 60_000), {
      coverage: 0.9, unattributedMs: 0, voicedMs: 1000, durationMs: 0,
    })
    expect(out.includes('these overlap')).toBe(false)
  })
})
