// What leaves the machine when Miles clicks Copy.
//
// THE FIXTURE IS THE POINT. v1's fixture put the confirmed-absent name ONLY in
// `## Attendees`, so `expect(out).not.toContain('Richard Jenkins')` passed while
// 14 unasserted names shipped in the transcript of every real meeting. Third time
// in one day a green suite hid a defect because the fixture could not reproduce
// production, so this one carries the real shapes: a `[Name]:` transcript label
// for an unasserted voice, that same name in the prose, the `<details>` wrapper
// (160 of 227 real scribes), the generator stamp (161), the
// `G2 Speaker-Separated Transcript` heading (113), and an unrecognised section.

import { describe, expect, it } from 'vitest'
import {
  SHARE_COVERAGE_FLOOR,
  cleanBody,
  clipboardFull,
  clipboardSummary,
  meetingDate,
  parseScribe,
  renderAttendees,
  renderProvenance,
  type AttendeeLine,
} from './meeting-scribe-content.js'

/** Production-shaped: decorated transcript heading, scaffold, stamp, extras. */
const SCRIBE = `# IJO Post-Mortem, Edge Saturation Stalls Deals (G2)

| Duration | 26 minutes |

## Attendees
- Richard Jenkins
- Fourteen others the review never confirmed

## Summary
Reviewed the IJO outcome. Jessica Thompson owns the booth follow-up.

## Topics Discussed
- Edge saturation
- Booth placement

## Decisions Made
- Retract the $199 claim; Tyler could not source the number.

## Action Items

### High Confidence
- [ ] Add a booth-placement requirement (Jessica Thompson)

### Needs Review
- [ ] \`[REVIEW]\` Chase the pricing source

## Granola Structured Notes (canonical)
Miles's own write-up, which v1 threw away.

## G2 Speaker-Separated Transcript
<details>
<summary>Click to expand transcript</summary>

[MU]: So where did IJO land.
[Richard Jenkins]: Edge was everywhere on the floor.

</details>

---

*Generated by Meeting Intelligence System — 2026-08-07 13:01:02*
`

describe('parseScribe', () => {
  it('finds a transcript whose heading does not START with the word', () => {
    // 113 real scribes head it `G2 Speaker-Separated Transcript`. Prefix matching
    // — the obvious rule — misses every one of them.
    const s = parseScribe(SCRIBE)
    expect(s.transcript).toContain('Edge was everywhere on the floor')
  })

  it('strips the details wrapper and the generator stamp', () => {
    const s = parseScribe(SCRIBE)
    expect(s.transcript).not.toContain('<details>')
    expect(s.transcript).not.toContain('<summary>')
    expect(s.transcript).not.toContain('Generated by Meeting Intelligence')
    expect(s.transcript.trimEnd().endsWith('Edge was everywhere on the floor.')).toBe(true)
  })

  it('keeps sections it does not recognise instead of dropping them', () => {
    // v1 discarded 116,820 chars corpus-wide, including this one.
    const s = parseScribe(SCRIBE)
    expect(s.extras.map(x => x.heading)).toContain('Granola Structured Notes (canonical)')
    expect(s.extras.find(x => x.heading.startsWith('Granola'))!.body).toContain('threw away')
  })

  it('drops the unfloored Attendees list entirely', () => {
    const s = parseScribe(SCRIBE)
    expect(s.extras.map(x => x.heading)).not.toContain('Attendees')
  })

  it('keeps ### subheadings inside their parent section', () => {
    const s = parseScribe(SCRIBE)
    expect(s.actions).toContain('High Confidence')
    expect(s.actions).toContain('Needs Review')
    expect(s.sections.map(x => x.heading)).not.toContain('High Confidence')
  })

  it('does not treat a # inside a fenced code block as a heading', () => {
    const fenced = '# Real Title\n\n## Transcript\n[MU]: run this\n\n```sh\n# deploy.sh --force\n## not a heading\n```\n\n[MU]: done.\n'
    const s = parseScribe(fenced)
    expect(s.title).toBe('Real Title')
    expect(s.sections.map(x => x.heading)).toEqual(['Transcript'])
    expect(s.transcript).toContain('done.')
  })

  it('prefers the longest transcript when a file has two candidates', () => {
    const two = '# T\n\n## Transcript Enrichment (from raw recording)\nshort note.\n\n## G2 Speaker-Separated Transcript\n' + 'x'.repeat(400) + '\n'
    expect(parseScribe(two).transcript.length).toBeGreaterThan(300)
  })

  it('normalises CRLF', () => {
    const s = parseScribe('# T\r\n\r\n## Summary\r\nline one.\r\n')
    expect(s.summary).toBe('line one.')
  })

  it('treats a heading-less file as the summary', () => {
    const s = parseScribe('loose notes, no headings')
    expect(s.summary).toBe('loose notes, no headings')
  })

  it('survives an empty file', () => {
    const s = parseScribe('')
    expect(s.title).toBe('')
    expect(s.transcript).toBe('')
    expect(s.extras).toEqual([])
  })
})

describe('cleanBody', () => {
  it('drops a trailing rule orphaned by the stamp above it', () => {
    expect(cleanBody('text\n\n---\n\n*Generated by X — now*\n')).toBe('text')
  })
  it('leaves a rule that is real content alone', () => {
    expect(cleanBody('before\n\n---\n\nafter')).toBe('before\n\n---\n\nafter')
  })
})

const VOICES: AttendeeLine[] = [
  { label: 'MU', asserted: true, speakingMs: 600_000, share: 0.6 },
  { label: 'Gina Obert', asserted: true, speakingMs: 400_000, share: 0.4 },
  { label: 'Richard Jenkins', asserted: false, speakingMs: 30_000, share: null },
  { label: 'Ext', asserted: false, speakingMs: 120_000, share: null },
]
/** The review's UNION for the unnamed voices — deliberately LESS than 30+120. */
const UNION_MS = 100_000
const HIGH = { coverage: 0.9, unattributedMs: UNION_MS }
const LOW = { coverage: 0.105, unattributedMs: UNION_MS }

describe('renderAttendees', () => {
  it('names only asserted voices, with time and share', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).toContain('- MU: 10m · 60% of identified speech')
    expect(out).toContain('- Gina Obert: 6m 40s · 40% of identified speech')
  })

  it('NEVER names an unasserted voice in the attendee block', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).not.toContain('Richard Jenkins')
    expect(out).not.toContain('Ext')
  })

  // v1 summed per-voice figures and printed 30m 21s inside a 26-minute meeting.
  it('uses the review UNION, not the sum of per-voice times', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).toContain('- Unidentified: 1m 40s across 2 voices the review could not name')
    expect(out).not.toContain('2m 30s')
  })

  // The panel suppresses shares below this; the clipboard must too.
  it('SUPPRESSES shares below the coverage floor', () => {
    const out = renderAttendees(VOICES, LOW)
    expect(out).toContain('- MU: 10m')
    expect(out).not.toContain('%')
  })

  it('suppresses shares when coverage is unknown, failing closed', () => {
    expect(renderAttendees(VOICES, { coverage: null, unattributedMs: UNION_MS })).not.toContain('%')
  })

  it('emits no em dash or arrow, per the standing rule for generated copy', () => {
    const out = renderAttendees(VOICES, HIGH)
    expect(out).not.toContain('—')
    expect(out).not.toContain('→')
  })

  it('says so when nothing was identified', () => {
    expect(renderAttendees([], HIGH)).toBe('- (no voices identified)')
  })

  it('formats a whole minute without a bare 0s', () => {
    const one: AttendeeLine[] = [{ label: 'A', asserted: true, speakingMs: 60_000, share: 1 }]
    expect(renderAttendees(one, HIGH)).toContain('- A: 1m ·')
  })
})

describe('renderProvenance', () => {
  it('names the confirmed set as an allowlist', () => {
    const out = renderProvenance(VOICES, 0.9)
    expect(out).toContain('Voice matching confirmed: MU, Gina Obert.')
  })

  it('warns that any other name is unconfirmed, and may be merely mentioned', () => {
    const out = renderProvenance(VOICES, 0.9)
    expect(out).toContain('was NOT')
    expect(out).toContain('mentioned rather than people present')
  })

  it('states the coverage figure when it is below the floor', () => {
    expect(renderProvenance(VOICES, 0.105)).toContain('Only 11% of the voice')
  })

  it('is explicit when nobody was confirmed', () => {
    const none = VOICES.filter(v => !v.asserted)
    expect(renderProvenance(none, 0.05)).toContain('confirmed nobody')
  })
})

const INPUT = {
  title: 'IJO Post-Mortem',
  date: '2026-08-06',
  durationMin: 26,
  attendees: VOICES,
  scribe: parseScribe(SCRIBE),
  coverage: 0.105,
  unattributedMs: UNION_MS,
}

describe('clipboard forms', () => {
  it('summary omits the transcript but says that it did', () => {
    const out = clipboardSummary(INPUT)
    expect(out).toContain('## Who spoke')
    expect(out).not.toContain('Edge was everywhere on the floor')
    expect(out).toContain('Transcript omitted')
  })

  // THE BLOCKER. An unasserted name reaches the body legitimately (transcript
  // label, prose mention) — so the output MUST carry the correction with it.
  it('carries the provenance warning wherever an unasserted name can appear', () => {
    for (const out of [clipboardSummary(INPUT), clipboardFull(INPUT)]) {
      expect(out).toContain('Voice matching confirmed: MU, Gina Obert.')
      expect(out).toContain('was NOT confirmed')
    }
  })

  it('never lets the unfloored Attendees list through', () => {
    const out = clipboardFull(INPUT)
    expect(out).not.toContain('Fourteen others the review never confirmed')
  })

  it('full carries the transcript, scaffolding already stripped', () => {
    const out = clipboardFull(INPUT)
    expect(out).toContain('Edge was everywhere on the floor')
    expect(out).not.toContain('<details>')
    expect(out).not.toContain('Generated by Meeting Intelligence')
    expect(out.length).toBeGreaterThan(clipboardSummary(INPUT).length)
  })

  it('carries unrecognised sections into both forms', () => {
    for (const out of [clipboardSummary(INPUT), clipboardFull(INPUT)]) {
      expect(out).toContain('## Granola Structured Notes (canonical)')
      expect(out).toContain('threw away')
    }
  })

  it('reports no share anywhere when coverage is below the floor', () => {
    // 26-minute meeting at 10.5% coverage: v1 printed "100% of named speech".
    expect(clipboardFull(INPUT)).not.toContain('of identified speech')
  })

  it('reports shares when coverage clears the floor', () => {
    const out = clipboardFull({ ...INPUT, coverage: 0.9 })
    expect(out).toContain('% of identified speech')
  })

  it('says when a transcript genuinely does not exist', () => {
    const noTx = { ...INPUT, scribe: parseScribe('# T\n\n## Summary\nshort.') }
    expect(clipboardFull(noTx)).toContain('(no transcript in this scribe)')
    expect(clipboardSummary(noTx)).not.toContain('Transcript omitted')
  })

  it('omits an empty date or duration rather than printing a bare separator', () => {
    const bare = clipboardSummary({ ...INPUT, date: '', durationMin: 0 })
    expect(bare.split('\n')[1]).not.toMatch(/^\s*·/)
    expect(bare).not.toContain('0 minutes')
  })

  it('the floor is the same constant the panel uses', () => {
    expect(SHARE_COVERAGE_FLOOR).toBe(0.6)
  })
})

describe('meetingDate', () => {
  it('converts epoch milliseconds to a calendar date', () => {
    expect(meetingDate(1786123940914)).toMatch(/^\d{4}-\d{2}-\d{2}$/)
    expect(meetingDate(1786123940914)).not.toContain('1786')
  })
  it('tolerates epoch seconds and numeric strings', () => {
    expect(meetingDate(1786123940)).toBe(meetingDate(1786123940914))
    expect(meetingDate('1786123940914')).toBe(meetingDate(1786123940914))
  })
  it('accepts an ISO string', () => {
    expect(meetingDate('2026-08-07T12:00:00.000Z')).toMatch(/^2026-08-0[678]$/)
  })
  it('returns empty for junk, and for 0 or negative rather than 1969', () => {
    for (const x of [undefined, null, '', 'not a date', {}, NaN, 0, -1]) {
      expect(meetingDate(x)).toBe('')
    }
  })
})
